import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import Header from "@/comonents/Header/Header";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${geistMono.variable} h-full antialiased dark:bg-black`}>
      <body className="min-h-full flex flex-col bg-black">
        <Header />
        {children}
      </body>
    </html>
  );
}
